apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: boutique-kv-secrets
  namespace: boutique

spec:
  provider: azure
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "9a3cc953-3e77-4433-be69-e24b705c811b" # The Client ID of the AKS Kubelet Identity

    keyvaultName: "boutiquekv-7fwuuu" # The name of your Azure Key Vault
    tenantId: "823fc44f-0584-4327-8fc8-e26608640a83" # Your Azure Tenant ID
    objects:  |
      array:
        - |
          objectName: redis-password
          objectType: secret
