{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "podinfo.fullname" . }}
  labels:
    {{- include "podinfo.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }} # 👈 Grabs value from values.yaml (default: 2)
  selector:
    matchLabels:
      {{- include "podinfo.selectorLabels" . | nindent 6 }}
{{- end }}
