replicaCount: 4
resources:
  requests:
    cpu: 200m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

# Do not use Spot nodes in production to prevent unexpected evictions
tolerations: []
affinity: {}


autoscaling:
  minReplicas: 4
  maxReplicas: 15
  targetCPUUtilizationPercentage: 60