replicaCount: 2
image:
  repository: devacr1vzwhs.azurecr.io/podinfo
  pullPolicy: IfNotPresent
  tag: "1.0.5"
service:
  type: ClusterIP
  port: 9898
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 256Mi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
pdb:
  enabled: true
  minAvailable: 2
monitoring:
  enabled: true
  interval: 15s
tolerations: []
affinity: {}
