apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXM=

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc

spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 1Gi 

---

apiVersion: v1
kind: Service
metadata:
  name: db

spec: 
  type: ClusterIP
  ports:
    - port: 5432 # Port exposed by the Kubernetes Service.
      targetPort: 5432 # Port inside the PostgreSQL Pod/container.
  selector:
    app: db

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db

spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_USER
              value: postgres

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          resources:
            requests:
              cpu: 250m
              memory: 512Mi

            limits:
              cpu: 500m
              memory: 512Mi
          
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: postgres-pvc    
